// <auto-generated />
using System;
using Dinesaur.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dinesaur.Migrations
{
    [DbContext(typeof(DinesaurContext))]
    [Migration("20260118074144_New")]
    partial class New
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dinesaur.Data.DinesaurUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Contact")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a774b9c3-e3aa-48e1-b388-b3ff6a9ec638",
                            Contact = 91234567,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 41, 43, 276, DateTimeKind.Utc).AddTicks(4925),
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGB88B1Wkd16jLa+3o6tNZcLDJXLhEgmj2s7PIZBplq5yAtGtj0XVzcp0s71pW43vg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "35420c24-2af1-4aad-b9c8-1970094ec6ec",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "78049940-1b04-4965-890b-322d227a6833",
                            Contact = 97826235,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 41, 43, 353, DateTimeKind.Utc).AddTicks(342),
                            Email = "user@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "User",
                            NormalizedEmail = "USER@LOCALHOST.COM",
                            NormalizedUserName = "USER@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE/VwB5piV8QuUBPxY5zNGcaJsEFE8eWxmaqzP3nhzF5twTJdJnKuu5EzMFzeV0Oiw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b24a3dd0-bb87-4d80-9517-ceacaa700f7a",
                            TwoFactorEnabled = false,
                            UserName = "user@localhost.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7be1ac42-5f6c-48ef-8a0f-22719a3c60c1",
                            Contact = 82613992,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 41, 43, 410, DateTimeKind.Utc).AddTicks(6714),
                            Email = "Tomahawk@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Tomahawk Admin",
                            NormalizedEmail = "TOMAHAWK@GMAIL.COM",
                            NormalizedUserName = "TOMAHAWK@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEI7N0M+UCa44ZH2xusz5pdsxDO0QEiMlwRwQp96pnzLhstGUlMtRHaCIf5eOKnpN/w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f1d519cc-7440-43e7-bc28-e3945fe9144f",
                            TwoFactorEnabled = false,
                            UserName = "Tomahawk@gmail.com"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1b251a8a-0988-4fc0-9667-94db70e090a9",
                            Contact = 82613992,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 41, 43, 489, DateTimeKind.Utc).AddTicks(1094),
                            Email = "ButcherBlock@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "ButcherAdmin",
                            NormalizedEmail = "BUTCHERBLOCK@GMAIL.COM",
                            NormalizedUserName = "BUTCHERBLOCK@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELFl+gx5pi5kc1QfyabZBe20uR9Gt3ggPq3jiiBYw5oo5eVn3uJMr2rptoDsRYYMVA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "929f9231-6cf1-4e3a-8599-8b899974f106",
                            TwoFactorEnabled = false,
                            UserName = "ButcherBlock@gmail.com"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9b933caf-b366-4e84-bd9e-73f94018d00e",
                            Contact = 88706606,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 41, 43, 553, DateTimeKind.Utc).AddTicks(3531),
                            Email = "labula@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "LabulaAdmin",
                            NormalizedEmail = "LABULA@GMAIL.COM",
                            NormalizedUserName = "LABULA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM9xOkrhbF1mlDHA4Ch7xGkzD2pD6GhVdpqi8I98NpBp80Q4HGLkhv8xas//HF28eA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bf8d272a-6e77-4965-987d-0b437bb08f02",
                            TwoFactorEnabled = false,
                            UserName = "labula@gmail.com"
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "da4eb4a7-c7c6-4c92-9243-df3008703d09",
                            Contact = 94799101,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 41, 43, 619, DateTimeKind.Utc).AddTicks(4500),
                            Email = "chefhats@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "ChefHatsAdmin",
                            NormalizedEmail = "CHEFHATS@GMAIL.COM",
                            NormalizedUserName = "CHEFHATS@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG9LU66kIx6sxp32qx/PypLVkQZJPygprwaAuAglh4w2ku5x/DVxLVidFSIAh4dBAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d13c23cc-f1da-444e-a7cf-9aea86eea29e",
                            TwoFactorEnabled = false,
                            UserName = "chefhats@gmail.com"
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "925277f0-dfb3-447c-8243-7be3027b19a7",
                            Contact = 91234560,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 41, 43, 703, DateTimeKind.Utc).AddTicks(7361),
                            Email = "tdp@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "TDPAdmin",
                            NormalizedEmail = "TDP@GMAIL.COM",
                            NormalizedUserName = "TDP@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECtpJKqnQf3AiHVS+TgTeKmWHJ9WxngIF78CLxk4Li55mwmAe8RIwe3C3Yz5Cjr0dw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fe195352-b694-4303-b9af-e3dbe7fce800",
                            TwoFactorEnabled = false,
                            UserName = "tdp@gmail.com"
                        },
                        new
                        {
                            Id = "8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1b57c5cb-8965-418b-9fa7-77a51b42c721",
                            Contact = 96409718,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 41, 43, 760, DateTimeKind.Utc).AddTicks(6454),
                            Email = "oliverchay@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Oliver",
                            NormalizedEmail = "OLIVERCHAY@GMAIL.COM",
                            NormalizedUserName = "OLIVERCHAY@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBg1yQIX0p+6/JQCYsJ5IP4ohROWri10fGqrsutYNtpSyjVB081Gh2IWkWj6trOHow==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9f9ad329-2dfb-4540-9054-adf7ac8e2a5a",
                            TwoFactorEnabled = false,
                            UserName = "oliverchay@gmailcom"
                        },
                        new
                        {
                            Id = "9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dc31a5e8-72db-465a-b3e5-0a1cf787b30e",
                            Contact = 93278292,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 41, 43, 820, DateTimeKind.Utc).AddTicks(2369),
                            Email = "ryanneo@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Ryan",
                            NormalizedEmail = "RYANNEO@GMAIL.COM",
                            NormalizedUserName = "RYANNEO@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA54BQGQ1ZixQfYBfdFCaLHb0prPo8wTCd6VPsoLqItjDaQCBfTEUf856PrSouCArA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "39c16016-cd7a-4638-9e55-0a207bff435f",
                            TwoFactorEnabled = false,
                            UserName = "ryanneo@gmail.com"
                        },
                        new
                        {
                            Id = "10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c97dfdc8-b855-486b-96e2-bc2dec192dfb",
                            Contact = 97629623,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 41, 43, 878, DateTimeKind.Utc).AddTicks(8695),
                            Email = "dustindomingo@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dustin",
                            NormalizedEmail = "DUSTINDOMINGO@GMAIL.COM",
                            NormalizedUserName = "DUSTINDOMINGO@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMPJcjW0XPHd+gwUvDdPW2iM8Th1x1J+/j6PdeBKdpxpIeDlCfwXHT6yWryssoK0HA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "83812eb9-bc33-4668-9247-a5c0d13b0f58",
                            TwoFactorEnabled = false,
                            UserName = "dustindomingo@gmail.com"
                        },
                        new
                        {
                            Id = "11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "465b25ab-1d83-4adc-b30f-da73b18b3078",
                            Contact = 97237323,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 41, 43, 935, DateTimeKind.Utc).AddTicks(8098),
                            Email = "restaurantstaff@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "RestaurantStaff",
                            NormalizedEmail = "RESTAURANTSTAFF@localhost.COM",
                            NormalizedUserName = "RESTAURANTSTAFF@localhost.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELFA1pHpFRcZrW+cxHqS07IMAnnbcD1ZSGysH8ZqhtH5JpQYcgzpXYM9WkkqOjmjGg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9ddb5743-b0fc-4c2e-a826-284db3e9b088",
                            TwoFactorEnabled = false,
                            UserName = "restaurantstaff@localhost.com"
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.DinesaurUserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Contact")
                        .HasColumnType("int");

                    b.Property<string>("DinesaurUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DinesaurUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DinesaurUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contact = 97826235,
                            DinesaurUserID = "2",
                            DinesaurUserName = "User",
                            Email = "user@localhost.com"
                        },
                        new
                        {
                            Id = 2,
                            Contact = 96409718,
                            DinesaurUserID = "8",
                            DinesaurUserName = "Oliver",
                            Email = "user@localhost.com"
                        },
                        new
                        {
                            Id = 3,
                            Contact = 93278292,
                            DinesaurUserID = "9",
                            DinesaurUserName = "Ryan",
                            Email = "user@localhost.com"
                        },
                        new
                        {
                            Id = 4,
                            Contact = 97629623,
                            DinesaurUserID = "10",
                            DinesaurUserName = "Dustin",
                            Email = "dustindomingo@gmail.com"
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Food", b =>
                {
                    b.Property<int>("FoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<string>("StaffID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodID");

                    b.ToTable("Food");

                    b.HasData(
                        new
                        {
                            FoodID = 1,
                            Category = "Meat",
                            Cost = 3.5,
                            Description = "White meat",
                            FoodName = "Chicken",
                            Image = "[]",
                            MenuID = 9999,
                            StaffID = "999"
                        },
                        new
                        {
                            FoodID = 2,
                            Category = "Seafood",
                            Cost = 4.0,
                            Description = "Saba",
                            FoodName = "Fish",
                            Image = "[]",
                            MenuID = 999,
                            StaffID = "9999"
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Menu", b =>
                {
                    b.Property<int>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Catergories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.HasKey("MenuID");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            MenuID = 1,
                            Category = "",
                            Catergories = "[]",
                            RestaurantID = 999
                        },
                        new
                        {
                            MenuID = 2,
                            Category = "",
                            Catergories = "[]",
                            RestaurantID = 9998
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.PreOrder", b =>
                {
                    b.Property<int>("PreOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreOrderID"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.HasKey("PreOrderID");

                    b.ToTable("PreOrder");

                    b.HasData(
                        new
                        {
                            PreOrderID = 1,
                            Cost = 3.5,
                            MenuID = 1,
                            Remarks = "Please remove the onions",
                            ReservationID = 1
                        },
                        new
                        {
                            PreOrderID = 2,
                            Cost = 4.0,
                            MenuID = 2,
                            Remarks = "Please remove all vegetables",
                            ReservationID = 2
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.PreOrderItem", b =>
                {
                    b.Property<int>("PreorderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreorderItemID"));

                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.Property<int>("PreOrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("PreorderItemID");

                    b.ToTable("PreOrderItem");

                    b.HasData(
                        new
                        {
                            PreorderItemID = 1,
                            FoodID = 1,
                            PreOrderID = 1,
                            Quantity = 1
                        },
                        new
                        {
                            PreorderItemID = 2,
                            FoodID = 1,
                            PreOrderID = 1,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("Pax")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("Time")
                        .IsRequired()
                        .HasColumnType("time");

                    b.HasKey("ReservationID");

                    b.ToTable("Reservation");

                    b.HasData(
                        new
                        {
                            ReservationID = 1,
                            CustomerID = "8",
                            Date = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 4,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 0,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 2,
                            CustomerID = "8",
                            Date = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 2,
                            Remarks = "N/A",
                            RestaurantID = 2,
                            Status = 3,
                            Time = new TimeOnly(18, 30, 0)
                        },
                        new
                        {
                            ReservationID = 3,
                            CustomerID = "8",
                            Date = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 10,
                            Remarks = "1 Baby Chair",
                            RestaurantID = 1,
                            Status = 4,
                            Time = new TimeOnly(13, 30, 0)
                        },
                        new
                        {
                            ReservationID = 4,
                            CustomerID = "9",
                            Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 2,
                            Remarks = "N/A",
                            RestaurantID = 3,
                            Status = 0,
                            Time = new TimeOnly(14, 30, 0)
                        },
                        new
                        {
                            ReservationID = 5,
                            CustomerID = "9",
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 3,
                            Remarks = "N/A",
                            RestaurantID = 2,
                            Status = 3,
                            Time = new TimeOnly(19, 30, 0)
                        },
                        new
                        {
                            ReservationID = 6,
                            CustomerID = "9",
                            Date = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 5,
                            Remarks = "N/A",
                            RestaurantID = 3,
                            Status = 1,
                            Time = new TimeOnly(14, 30, 0)
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Restaurant", b =>
                {
                    b.Property<int>("RestaurantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantID"));

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("ClosingHours")
                        .HasColumnType("time");

                    b.Property<int?>("Contact")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("OpeningHours")
                        .HasColumnType("time");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantOwnerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RestaurantID");

                    b.ToTable("Restaurant");

                    b.HasData(
                        new
                        {
                            RestaurantID = 1,
                            AdminID = 1,
                            Category = "Western",
                            ClosingHours = new TimeOnly(22, 0, 0),
                            Contact = 82613992,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 41, 43, 276, DateTimeKind.Utc).AddTicks(4166),
                            Email = "tomahawk@gmail.com",
                            Location = "273, #01-06 Thomson Rd, Novena Gardens, Singapore 307644",
                            Logo = "[\"/Images/Tomahawk.jpeg\"]",
                            OpeningHours = new TimeOnly(12, 0, 0),
                            RestaurantName = "Tomahawk Contemporary Steakhouse",
                            RestaurantOwnerID = "3",
                            Status = 1
                        },
                        new
                        {
                            RestaurantID = 2,
                            AdminID = 1,
                            Category = "Fine Dining",
                            ClosingHours = new TimeOnly(21, 30, 0),
                            Contact = 64121816,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 41, 43, 276, DateTimeKind.Utc).AddTicks(4181),
                            Email = "ButcherBlock@gmail.com",
                            Location = "328 N Bridge Rd, #02-02 RAFFLES ARCADE, Singapore 188719",
                            Logo = "[\"/Images/Butcher.jpg\"]",
                            OpeningHours = new TimeOnly(12, 0, 0),
                            RestaurantName = "Butcher's Block",
                            RestaurantOwnerID = "4",
                            Status = 1
                        },
                        new
                        {
                            RestaurantID = 3,
                            AdminID = 1,
                            Category = "HotPot",
                            ClosingHours = new TimeOnly(22, 30, 0),
                            Contact = 88706606,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 41, 43, 276, DateTimeKind.Utc).AddTicks(4186),
                            Email = "labula@gmail.com",
                            Location = "681 Punggol Dr., #01-07, Singapore 820681",
                            Logo = "[\"/Images/LABULA.jpg\"]",
                            OpeningHours = new TimeOnly(10, 30, 0),
                            RestaurantName = "辣不辣 Labula Mala Sichuan Restaurant",
                            RestaurantOwnerID = "5",
                            Status = 1
                        },
                        new
                        {
                            RestaurantID = 4,
                            AdminID = 1,
                            Category = "Western",
                            ClosingHours = new TimeOnly(22, 0, 0),
                            Contact = 94799101,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 41, 43, 276, DateTimeKind.Utc).AddTicks(4190),
                            Email = "chefhats@gmail.com",
                            Location = "21 Hougang St 51, #01-01A Hougang GREEN Shopping Mall, Singapore 538719",
                            Logo = "[\"/Images/Chef.jpg\"]",
                            OpeningHours = new TimeOnly(10, 0, 0),
                            RestaurantName = "Chef's Hats",
                            RestaurantOwnerID = "6",
                            Status = 0
                        },
                        new
                        {
                            RestaurantID = 5,
                            AdminID = 1,
                            Category = "Dessert",
                            ClosingHours = new TimeOnly(17, 30, 0),
                            Contact = 94350556,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 41, 43, 276, DateTimeKind.Utc).AddTicks(4194),
                            Email = "tdp@gmail.com",
                            Location = "406 Tampines Street 41, #01-23 Sun Plaza Green, Singapore 520406",
                            Logo = "[\"/Images/tdp.jpeg\"]",
                            OpeningHours = new TimeOnly(11, 30, 0),
                            RestaurantName = "The Dessert Party",
                            RestaurantOwnerID = "7",
                            Status = 2
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<string>("ReviewTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ReviewID = 1,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 18, 15, 41, 43, 276, DateTimeKind.Local).AddTicks(4621),
                            Description = "Bad",
                            Rating = 2.5,
                            RestaurantID = 1,
                            ReviewTitle = "Bad",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "3",
                            Name = "RestaurantStaff",
                            NormalizedName = "RESTAURANTSTAFF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "6",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "7",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "8",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "9",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "10",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "11",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Dinesaur.Data.DinesaurUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Dinesaur.Data.DinesaurUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dinesaur.Data.DinesaurUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Dinesaur.Data.DinesaurUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
