// <auto-generated />
using System;
using Dinesaur.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dinesaur.Migrations
{
    [DbContext(typeof(DinesaurContext))]
    [Migration("20260118072315_c")]
    partial class c
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dinesaur.Data.DinesaurUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Contact")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5da0b5d3-7f62-4199-b599-be85e73cf0f1",
                            Contact = 91234567,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 23, 14, 312, DateTimeKind.Utc).AddTicks(4517),
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECZV/uGPVl0sHGlUAPLY5ESE1JVwDrFDD0zb2keNO8UBJ1yu4z3esr0a7wUBbA0C+g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4a162695-f5ee-4eec-8fc2-08a6f81a269a",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d1d0c9ca-4e43-410e-9154-abc9de9713e0",
                            Contact = 97826235,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 23, 14, 369, DateTimeKind.Utc).AddTicks(9479),
                            Email = "user@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "User",
                            NormalizedEmail = "USER@LOCALHOST.COM",
                            NormalizedUserName = "USER@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENHsAbtXGkcpGAW0OFeAM5EvO3NA3GziIUxWTTM4aQfSi4hdxFSLwkMQut53u5/Pfw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "47bd808c-30b3-428d-b95f-bb8cc541b9cf",
                            TwoFactorEnabled = false,
                            UserName = "user@localhost.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b58d6498-7074-4c7b-9a69-b0d1aef22e50",
                            Contact = 82613992,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 23, 14, 432, DateTimeKind.Utc).AddTicks(7456),
                            Email = "Tomahawk@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Tomahawk Admin",
                            NormalizedEmail = "TOMAHAWK@GMAIL.COM",
                            NormalizedUserName = "TOMAHAWK@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO+MHpEM2YuF0+UDu99C/CEz8IP6Z//BjS5zr1ReiKMC4zR7sLLB3YUpDNnFKHne/w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bac088a5-72d9-4669-bf95-0151f9eac523",
                            TwoFactorEnabled = false,
                            UserName = "Tomahawk@gmail.com"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "eadbb051-6a9e-4c95-b032-d3303c7e8a4c",
                            Contact = 82613992,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 23, 14, 491, DateTimeKind.Utc).AddTicks(8645),
                            Email = "ButcherBlock@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "ButcherAdmin",
                            NormalizedEmail = "BUTCHERBLOCK@GMAIL.COM",
                            NormalizedUserName = "BUTCHERBLOCK@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPJV8xbfTaI7SLUQ93LNC04NqEHrzjT/BAzKrHXyc0PoJ0BXBYWj7dskiLQr1f0NxA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "208b954b-b586-4181-bd11-22643d033340",
                            TwoFactorEnabled = false,
                            UserName = "ButcherBlock@gmail.com"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "df2e0b27-7447-49c3-b7f6-b929574b06d5",
                            Contact = 88706606,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 23, 14, 553, DateTimeKind.Utc).AddTicks(3095),
                            Email = "labula@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "LabulaAdmin",
                            NormalizedEmail = "LABULA@GMAIL.COM",
                            NormalizedUserName = "LABULA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKkwWRX2CXKbhkh6WRiA2ZRdUx4jOJ1ydeObrIjspK4ZlSSbYYeuM9nEC+N08XkgaQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1d37847e-273f-43cf-92f8-561b6573dd66",
                            TwoFactorEnabled = false,
                            UserName = "labula@gmail.com"
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "38eada82-da64-44cf-8b85-ebe8d2741903",
                            Contact = 94799101,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 23, 14, 621, DateTimeKind.Utc).AddTicks(2872),
                            Email = "chefhats@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "ChefHatsAdmin",
                            NormalizedEmail = "CHEFHATS@GMAIL.COM",
                            NormalizedUserName = "CHEFHATS@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBG1O7PXvNnloCTworEVpVlWvhAsyxK3X07Buolx/nmOhkKJSYVR8WwKKJvYDSTvCg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3a7a3599-3b50-4ec8-9185-e667936c0db7",
                            TwoFactorEnabled = false,
                            UserName = "chefhats@gmail.com"
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "39248ef6-108b-4420-b83a-b25eacf509bd",
                            Contact = 91234560,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 23, 14, 689, DateTimeKind.Utc).AddTicks(2064),
                            Email = "tdp@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "TDPAdmin",
                            NormalizedEmail = "TDP@GMAIL.COM",
                            NormalizedUserName = "TDP@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKfSCpU6kgbBEdRiSJy6XEDmEhJwkboZqKdEVQ7QhDsJDHgOtxlZUsN4CjTEc10qHA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9ed59dc7-a0d1-4b2e-975a-e7d54cd321b1",
                            TwoFactorEnabled = false,
                            UserName = "tdp@gmail.com"
                        },
                        new
                        {
                            Id = "8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e3762d78-f365-4e27-907c-656064ed9c5d",
                            Contact = 96409718,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 23, 14, 746, DateTimeKind.Utc).AddTicks(2556),
                            Email = "oliverchay@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Oliver",
                            NormalizedEmail = "OLIVERCHAY@GMAIL.COM",
                            NormalizedUserName = "OLIVERCHAY@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL9d8AF/g9AdP3jWvO1W7sbdc/yP174WN8JuzuONpvJMpshgTvFNLAHytLyEHIz2kQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "de78f588-078b-42ae-b091-02a1e792377f",
                            TwoFactorEnabled = false,
                            UserName = "oliverchay@gmailcom"
                        },
                        new
                        {
                            Id = "9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "86e7935f-7da0-48bc-bff2-afd499c63da7",
                            Contact = 93278292,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 23, 14, 810, DateTimeKind.Utc).AddTicks(7061),
                            Email = "ryanneo@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Ryan",
                            NormalizedEmail = "RYANNEO@GMAIL.COM",
                            NormalizedUserName = "RYANNEO@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAP21zOwlRD7DywehxnxIvOnVcW7a3IAUZ/VcrVgyIXE0YykY/I1nweHSnDazSt/Rg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "51848b75-e7b1-4366-9826-5294ed4b8e6b",
                            TwoFactorEnabled = false,
                            UserName = "ryanneo@gmail.com"
                        },
                        new
                        {
                            Id = "10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cdf159e1-8a3e-4dfb-a2cb-d732a62c512b",
                            Contact = 97629623,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 23, 14, 870, DateTimeKind.Utc).AddTicks(274),
                            Email = "dustindomingo@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dustin",
                            NormalizedEmail = "DUSTINDOMINGO@GMAIL.COM",
                            NormalizedUserName = "DUSTINDOMINGO@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJMEJJfIC6G08rSIgRk3YJx0i375qjiNaSedmTZizJQf+v4azqBFstaFdg7QSmQqXA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eb0c2ccb-fb63-4b1d-97f1-24a92c82210e",
                            TwoFactorEnabled = false,
                            UserName = "dustindomingo@gmail.com"
                        },
                        new
                        {
                            Id = "11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4d03635f-47f7-483e-be2b-10bbde73714b",
                            Contact = 97237323,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 23, 14, 930, DateTimeKind.Utc).AddTicks(1419),
                            Email = "restaurantstaff@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "RestaurantStaff",
                            NormalizedEmail = "RESTAURANTSTAFF@localhost.COM",
                            NormalizedUserName = "RESTAURANTSTAFF@localhost.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFT7SRLfaen/RcXk0mK13TIAtT0UFOhrzq+nwVnEfZJWturVZKIeEWw5BujmjtpmVA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e27b65d3-48c2-440a-8272-8b7233fda675",
                            TwoFactorEnabled = false,
                            UserName = "restaurantstaff@localhost.com"
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.DinesaurUserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Contact")
                        .HasColumnType("int");

                    b.Property<string>("DinesaurUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DinesaurUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DinesaurUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contact = 97826235,
                            DinesaurUserID = "2",
                            DinesaurUserName = "User",
                            Email = "user@localhost.com"
                        },
                        new
                        {
                            Id = 2,
                            Contact = 96409718,
                            DinesaurUserID = "8",
                            DinesaurUserName = "Oliver",
                            Email = "user@localhost.com"
                        },
                        new
                        {
                            Id = 3,
                            Contact = 93278292,
                            DinesaurUserID = "9",
                            DinesaurUserName = "Ryan",
                            Email = "user@localhost.com"
                        },
                        new
                        {
                            Id = 4,
                            Contact = 97629623,
                            DinesaurUserID = "10",
                            DinesaurUserName = "Dustin",
                            Email = "dustindomingo@gmail.com"
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Food", b =>
                {
                    b.Property<int>("FoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<string>("StaffID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodID");

                    b.ToTable("Food");

                    b.HasData(
                        new
                        {
                            FoodID = 1,
                            Category = "Meat",
                            Cost = 3.5,
                            Description = "White meat",
                            FoodName = "Chicken",
                            Image = "[]",
                            MenuID = 9999,
                            StaffID = "999"
                        },
                        new
                        {
                            FoodID = 2,
                            Category = "Seafood",
                            Cost = 4.0,
                            Description = "Saba",
                            FoodName = "Fish",
                            Image = "[]",
                            MenuID = 999,
                            StaffID = "9999"
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Menu", b =>
                {
                    b.Property<int>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Catergories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.HasKey("MenuID");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            MenuID = 1,
                            Category = "",
                            Catergories = "[]",
                            RestaurantID = 999
                        },
                        new
                        {
                            MenuID = 2,
                            Category = "",
                            Catergories = "[]",
                            RestaurantID = 9998
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.PreOrder", b =>
                {
                    b.Property<int>("PreOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreOrderID"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.HasKey("PreOrderID");

                    b.ToTable("PreOrder");

                    b.HasData(
                        new
                        {
                            PreOrderID = 1,
                            Cost = 3.5,
                            MenuID = 1,
                            Remarks = "Please remove the onions",
                            ReservationID = 1
                        },
                        new
                        {
                            PreOrderID = 2,
                            Cost = 4.0,
                            MenuID = 2,
                            Remarks = "Please remove all vegetables",
                            ReservationID = 2
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.PreOrderItem", b =>
                {
                    b.Property<int>("PreorderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreorderItemID"));

                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.Property<int>("PreOrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("PreorderItemID");

                    b.ToTable("PreOrderItem");

                    b.HasData(
                        new
                        {
                            PreorderItemID = 1,
                            FoodID = 1,
                            PreOrderID = 1,
                            Quantity = 1
                        },
                        new
                        {
                            PreorderItemID = 2,
                            FoodID = 1,
                            PreOrderID = 1,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("Pax")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("Time")
                        .IsRequired()
                        .HasColumnType("time");

                    b.HasKey("ReservationID");

                    b.ToTable("Reservation");

                    b.HasData(
                        new
                        {
                            ReservationID = 1,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 9, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 4,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 1,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 2,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 2,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 0,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 3,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 13, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 3,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 3,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 4,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 4,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 0,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 5,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 2,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 1,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 6,
                            CustomerID = "2",
                            Date = new DateTime(2025, 12, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 2,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 3,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 7,
                            CustomerID = "2",
                            Date = new DateTime(2025, 12, 22, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 4,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 3,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 8,
                            CustomerID = "2",
                            Date = new DateTime(2025, 12, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 3,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 3,
                            Time = new TimeOnly(12, 30, 0)
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Restaurant", b =>
                {
                    b.Property<int>("RestaurantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantID"));

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("ClosingHours")
                        .HasColumnType("time");

                    b.Property<int?>("Contact")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("OpeningHours")
                        .HasColumnType("time");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantOwnerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RestaurantID");

                    b.ToTable("Restaurant");

                    b.HasData(
                        new
                        {
                            RestaurantID = 1,
                            AdminID = 1,
                            Category = "Western",
                            ClosingHours = new TimeOnly(22, 0, 0),
                            Contact = 82613992,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 23, 14, 312, DateTimeKind.Utc).AddTicks(4140),
                            Email = "tomahawk@gmail.com",
                            Location = "273, #01-06 Thomson Rd, Novena Gardens, Singapore 307644",
                            Logo = "[\"/Images/Tomahawk.jpeg\"]",
                            OpeningHours = new TimeOnly(12, 0, 0),
                            RestaurantName = "Tomahawk Contemporary Steakhouse",
                            RestaurantOwnerID = "3",
                            Status = 1
                        },
                        new
                        {
                            RestaurantID = 2,
                            AdminID = 1,
                            Category = "Fine Dining",
                            ClosingHours = new TimeOnly(21, 30, 0),
                            Contact = 64121816,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 23, 14, 312, DateTimeKind.Utc).AddTicks(4154),
                            Email = "ButcherBlock@gmail.com",
                            Location = "328 N Bridge Rd, #02-02 RAFFLES ARCADE, Singapore 188719",
                            Logo = "[\"/Images/Butcher.jpg\"]",
                            OpeningHours = new TimeOnly(12, 0, 0),
                            RestaurantName = "Butcher's Block",
                            RestaurantOwnerID = "4",
                            Status = 1
                        },
                        new
                        {
                            RestaurantID = 3,
                            AdminID = 1,
                            Category = "HotPot",
                            ClosingHours = new TimeOnly(22, 30, 0),
                            Contact = 88706606,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 23, 14, 312, DateTimeKind.Utc).AddTicks(4159),
                            Email = "labula@gmail.com",
                            Location = "681 Punggol Dr., #01-07, Singapore 820681",
                            Logo = "[\"/Images/LABULA.jpg\"]",
                            OpeningHours = new TimeOnly(10, 30, 0),
                            RestaurantName = "辣不辣 Labula Mala Sichuan Restaurant",
                            RestaurantOwnerID = "5",
                            Status = 1
                        },
                        new
                        {
                            RestaurantID = 4,
                            AdminID = 1,
                            Category = "Western",
                            ClosingHours = new TimeOnly(22, 0, 0),
                            Contact = 94799101,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 23, 14, 312, DateTimeKind.Utc).AddTicks(4163),
                            Email = "chefhats@gmail.com",
                            Location = "21 Hougang St 51, #01-01A Hougang GREEN Shopping Mall, Singapore 538719",
                            Logo = "[\"/Images/Chef.jpg\"]",
                            OpeningHours = new TimeOnly(10, 0, 0),
                            RestaurantName = "Chef's Hats",
                            RestaurantOwnerID = "6",
                            Status = 0
                        },
                        new
                        {
                            RestaurantID = 5,
                            AdminID = 1,
                            Category = "Dessert",
                            ClosingHours = new TimeOnly(17, 30, 0),
                            Contact = 94350556,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 23, 14, 312, DateTimeKind.Utc).AddTicks(4167),
                            Email = "tdp@gmail.com",
                            Location = "406 Tampines Street 41, #01-23 Sun Plaza Green, Singapore 520406",
                            Logo = "[\"/Images/tdp.jpeg\"]",
                            OpeningHours = new TimeOnly(11, 30, 0),
                            RestaurantName = "The Dessert Party",
                            RestaurantOwnerID = "7",
                            Status = 2
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<string>("ReviewTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ReviewID = 1,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 18, 15, 23, 14, 312, DateTimeKind.Local).AddTicks(4276),
                            Description = "Bad",
                            Rating = 2.5,
                            RestaurantID = 1,
                            ReviewTitle = "Bad",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "3",
                            Name = "RestaurantStaff",
                            NormalizedName = "RESTAURANTSTAFF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "6",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "7",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "8",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "9",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "10",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "11",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Dinesaur.Data.DinesaurUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Dinesaur.Data.DinesaurUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dinesaur.Data.DinesaurUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Dinesaur.Data.DinesaurUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
