// <auto-generated />
using System;
using Dinesaur.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dinesaur.Migrations
{
    [DbContext(typeof(DinesaurContext))]
    [Migration("20260118071740_b")]
    partial class b
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dinesaur.Data.DinesaurUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Contact")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4d49fe1a-12bb-4873-8ee3-c7ceddc45665",
                            Contact = 91234567,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 17, 38, 20, DateTimeKind.Utc).AddTicks(6145),
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEQibLhguCz8jKSrKSxZ0uHrtVYA9GVw1zXan7B7DrzERK58VG2XGwEY/PUsoPUlDg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fe1aaf30-c84f-4241-a3ad-be3bfb6cba3c",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "13dafd5b-4c94-47e5-a999-f2e395b60745",
                            Contact = 97826235,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 17, 38, 80, DateTimeKind.Utc).AddTicks(1483),
                            Email = "user@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "User",
                            NormalizedEmail = "USER@LOCALHOST.COM",
                            NormalizedUserName = "USER@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIjS7drYH606Q2n3N/a0rQdW3lYsdkPxW2Ga8rLL2DRHSNwOPWTQ9BQSfGkrIv8W6Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2d19ca83-d9f5-4bdc-9442-59355968d907",
                            TwoFactorEnabled = false,
                            UserName = "user@localhost.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4c405678-2d9d-4b75-bd5a-06e39288c49a",
                            Contact = 82613992,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 17, 38, 140, DateTimeKind.Utc).AddTicks(236),
                            Email = "Tomahawk@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Tomahawk Admin",
                            NormalizedEmail = "TOMAHAWK@GMAIL.COM",
                            NormalizedUserName = "TOMAHAWK@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIPZUJ9UoZSR9h4MkQJuochRMAX5DqvOBZ03ICvTlHc7b460xc9FY8/ElrP7SNYXFg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ade3a8a2-5a68-4367-9db7-f33129247933",
                            TwoFactorEnabled = false,
                            UserName = "Tomahawk@gmail.com"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5ffb413d-1fd4-45ee-8e17-3d2febf8b306",
                            Contact = 82613992,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 17, 38, 210, DateTimeKind.Utc).AddTicks(7312),
                            Email = "ButcherBlock@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "ButcherAdmin",
                            NormalizedEmail = "BUTCHERBLOCK@GMAIL.COM",
                            NormalizedUserName = "BUTCHERBLOCK@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDz1CT+hdhYpdTJvTlhBRPsdoGaPkg1wZqAOwrs4V+VY+MN2B+1Pw8J5/wa/reVUYQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d6df28d4-221a-4842-a962-23e9b4a09b39",
                            TwoFactorEnabled = false,
                            UserName = "ButcherBlock@gmail.com"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dab20959-1f4b-4c93-8ae8-2bd3f3877d26",
                            Contact = 88706606,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 17, 38, 273, DateTimeKind.Utc).AddTicks(9313),
                            Email = "labula@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "LabulaAdmin",
                            NormalizedEmail = "LABULA@GMAIL.COM",
                            NormalizedUserName = "LABULA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG0uBoptzaL2XHpPd+bLkoosvUJhb6e3FZVBhy//nBrPQUeIMnu1ZXXQXwJglHaEuQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9f5e7258-1a65-47a6-b186-e10aa557d90e",
                            TwoFactorEnabled = false,
                            UserName = "labula@gmail.com"
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "42f80519-454d-4ef8-b2d5-0dc2b52cc024",
                            Contact = 94799101,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 17, 38, 337, DateTimeKind.Utc).AddTicks(7225),
                            Email = "chefhats@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "ChefHatsAdmin",
                            NormalizedEmail = "CHEFHATS@GMAIL.COM",
                            NormalizedUserName = "CHEFHATS@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJtdBaox/nupeUJB0eiPaEOfWQ0A8yCvv4fw7OaaPBBDxtrFfLfN7WW3A/2l4mGQuQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bfced823-1587-4da2-90e9-11539ac3cc95",
                            TwoFactorEnabled = false,
                            UserName = "chefhats@gmail.com"
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "98c31ad3-f30f-4693-b643-16320fe07175",
                            Contact = 91234560,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 17, 38, 403, DateTimeKind.Utc).AddTicks(17),
                            Email = "tdp@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "TDPAdmin",
                            NormalizedEmail = "TDP@GMAIL.COM",
                            NormalizedUserName = "TDP@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENEDEjzh3NUJoFxHNM3CCcIVQSruenIJdYLrO9JHRS3+gCb7qwqR91+GTAdeByJSBA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d7f4f2fe-6311-4cbf-870f-0d0763064b4d",
                            TwoFactorEnabled = false,
                            UserName = "tdp@gmail.com"
                        },
                        new
                        {
                            Id = "8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c6c4326e-5b84-4519-bae5-44f35773e26c",
                            Contact = 96409718,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 17, 38, 466, DateTimeKind.Utc).AddTicks(2321),
                            Email = "oliverchay@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Oliver",
                            NormalizedEmail = "OLIVERCHAY@GMAIL.COM",
                            NormalizedUserName = "OLIVERCHAY@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM4gRcikAx8p1BBuAqFBefVgxh9s1W3TEjvEvkG1txxKGfKHmzbSA9RfL8P6pgxzAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e7bf079c-4936-4bd8-aa12-f4d34f3c14b2",
                            TwoFactorEnabled = false,
                            UserName = "oliverchay@gmailcom"
                        },
                        new
                        {
                            Id = "9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "023ed53e-cfca-44c4-a504-49ffd2ec3b68",
                            Contact = 93278292,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 17, 38, 526, DateTimeKind.Utc).AddTicks(560),
                            Email = "ryanneo@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Ryan",
                            NormalizedEmail = "RYANNEO@GMAIL.COM",
                            NormalizedUserName = "RYANNEO@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAzxvCG6nWqaEUIau8eBVQC+8BGyzwsTJvZ0BqLE0FejznFJ9AiLx7W/Tv3xSqj+Dg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a2520724-2a33-49be-8f9e-f1937a2f311d",
                            TwoFactorEnabled = false,
                            UserName = "ryanneo@gmail.com"
                        },
                        new
                        {
                            Id = "10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3fb9e83a-404a-4707-8365-85e226e6bbb0",
                            Contact = 97629623,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 17, 38, 591, DateTimeKind.Utc).AddTicks(1086),
                            Email = "dustindomingo@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dustin",
                            NormalizedEmail = "DUSTINDOMINGO@GMAIL.COM",
                            NormalizedUserName = "DUSTINDOMINGO@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEp7vRdLmOhPwiDroqh1Iff4G9XPc1pocyj8/YFBBJB7ZXX5jvVdDpQizUStJcgWpQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8e76e3be-e39b-4336-9091-3c2d1030ae1b",
                            TwoFactorEnabled = false,
                            UserName = "dustindomingo@gmail.com"
                        },
                        new
                        {
                            Id = "11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7be568b1-dacf-4fec-9328-2c534aa5616f",
                            Contact = 97237323,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 17, 38, 654, DateTimeKind.Utc).AddTicks(4355),
                            Email = "restaurantstaff@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "RestaurantStaff",
                            NormalizedEmail = "RESTAURANTSTAFF@GMAIL.COM",
                            NormalizedUserName = "RESTAURANTSTAFF@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEh3jiI/NQ2ztoeIrTOy4qV4Lh3YeGw4J/NH9rP3ofqKfkludlymCgibKE5kEtVT1w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8c08e102-3b22-403c-be14-4c7b27d90447",
                            TwoFactorEnabled = false,
                            UserName = "restaurantstaff@localhost.com"
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.DinesaurUserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Contact")
                        .HasColumnType("int");

                    b.Property<string>("DinesaurUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DinesaurUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DinesaurUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contact = 97826235,
                            DinesaurUserID = "2",
                            DinesaurUserName = "User",
                            Email = "user@localhost.com"
                        },
                        new
                        {
                            Id = 2,
                            Contact = 96409718,
                            DinesaurUserID = "8",
                            DinesaurUserName = "Oliver",
                            Email = "user@localhost.com"
                        },
                        new
                        {
                            Id = 3,
                            Contact = 93278292,
                            DinesaurUserID = "9",
                            DinesaurUserName = "Ryan",
                            Email = "user@localhost.com"
                        },
                        new
                        {
                            Id = 4,
                            Contact = 97629623,
                            DinesaurUserID = "10",
                            DinesaurUserName = "Dustin",
                            Email = "dustindomingo@gmail.com"
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Food", b =>
                {
                    b.Property<int>("FoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<string>("StaffID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodID");

                    b.ToTable("Food");

                    b.HasData(
                        new
                        {
                            FoodID = 1,
                            Category = "Meat",
                            Cost = 3.5,
                            Description = "White meat",
                            FoodName = "Chicken",
                            Image = "[]",
                            MenuID = 9999,
                            StaffID = "999"
                        },
                        new
                        {
                            FoodID = 2,
                            Category = "Seafood",
                            Cost = 4.0,
                            Description = "Saba",
                            FoodName = "Fish",
                            Image = "[]",
                            MenuID = 999,
                            StaffID = "9999"
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Menu", b =>
                {
                    b.Property<int>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Catergories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.HasKey("MenuID");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            MenuID = 1,
                            Category = "",
                            Catergories = "[]",
                            RestaurantID = 999
                        },
                        new
                        {
                            MenuID = 2,
                            Category = "",
                            Catergories = "[]",
                            RestaurantID = 9998
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.PreOrder", b =>
                {
                    b.Property<int>("PreOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreOrderID"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.HasKey("PreOrderID");

                    b.ToTable("PreOrder");

                    b.HasData(
                        new
                        {
                            PreOrderID = 1,
                            Cost = 3.5,
                            MenuID = 1,
                            Remarks = "Please remove the onions",
                            ReservationID = 1
                        },
                        new
                        {
                            PreOrderID = 2,
                            Cost = 4.0,
                            MenuID = 2,
                            Remarks = "Please remove all vegetables",
                            ReservationID = 2
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.PreOrderItem", b =>
                {
                    b.Property<int>("PreorderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreorderItemID"));

                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.Property<int>("PreOrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("PreorderItemID");

                    b.ToTable("PreOrderItem");

                    b.HasData(
                        new
                        {
                            PreorderItemID = 1,
                            FoodID = 1,
                            PreOrderID = 1,
                            Quantity = 1
                        },
                        new
                        {
                            PreorderItemID = 2,
                            FoodID = 1,
                            PreOrderID = 1,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("Pax")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("Time")
                        .IsRequired()
                        .HasColumnType("time");

                    b.HasKey("ReservationID");

                    b.ToTable("Reservation");

                    b.HasData(
                        new
                        {
                            ReservationID = 1,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 9, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 4,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 1,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 2,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 2,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 0,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 3,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 13, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 3,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 3,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 4,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 4,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 0,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 5,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 2,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 1,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 6,
                            CustomerID = "2",
                            Date = new DateTime(2025, 12, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 2,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 3,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 7,
                            CustomerID = "2",
                            Date = new DateTime(2025, 12, 22, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 4,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 3,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 8,
                            CustomerID = "2",
                            Date = new DateTime(2025, 12, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 3,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 3,
                            Time = new TimeOnly(12, 30, 0)
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Restaurant", b =>
                {
                    b.Property<int>("RestaurantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantID"));

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("ClosingHours")
                        .HasColumnType("time");

                    b.Property<int?>("Contact")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("OpeningHours")
                        .HasColumnType("time");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantOwnerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RestaurantID");

                    b.ToTable("Restaurant");

                    b.HasData(
                        new
                        {
                            RestaurantID = 1,
                            AdminID = 1,
                            Category = "Western",
                            ClosingHours = new TimeOnly(22, 0, 0),
                            Contact = 82613992,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 17, 38, 20, DateTimeKind.Utc).AddTicks(5758),
                            Email = "tomahawk@gmail.com",
                            Location = "273, #01-06 Thomson Rd, Novena Gardens, Singapore 307644",
                            Logo = "[\"/Images/Tomahawk.jpeg\"]",
                            OpeningHours = new TimeOnly(12, 0, 0),
                            RestaurantName = "Tomahawk Contemporary Steakhouse",
                            RestaurantOwnerID = "3",
                            Status = 1
                        },
                        new
                        {
                            RestaurantID = 2,
                            AdminID = 1,
                            Category = "Fine Dining",
                            ClosingHours = new TimeOnly(21, 30, 0),
                            Contact = 64121816,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 17, 38, 20, DateTimeKind.Utc).AddTicks(5772),
                            Email = "ButcherBlock@gmail.com",
                            Location = "328 N Bridge Rd, #02-02 RAFFLES ARCADE, Singapore 188719",
                            Logo = "[\"/Images/Butcher.jpg\"]",
                            OpeningHours = new TimeOnly(12, 0, 0),
                            RestaurantName = "Butcher's Block",
                            RestaurantOwnerID = "4",
                            Status = 1
                        },
                        new
                        {
                            RestaurantID = 3,
                            AdminID = 1,
                            Category = "HotPot",
                            ClosingHours = new TimeOnly(22, 30, 0),
                            Contact = 88706606,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 17, 38, 20, DateTimeKind.Utc).AddTicks(5777),
                            Email = "labula@gmail.com",
                            Location = "681 Punggol Dr., #01-07, Singapore 820681",
                            Logo = "[\"/Images/LABULA.jpg\"]",
                            OpeningHours = new TimeOnly(10, 30, 0),
                            RestaurantName = "辣不辣 Labula Mala Sichuan Restaurant",
                            RestaurantOwnerID = "5",
                            Status = 1
                        },
                        new
                        {
                            RestaurantID = 4,
                            AdminID = 1,
                            Category = "Western",
                            ClosingHours = new TimeOnly(22, 0, 0),
                            Contact = 94799101,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 17, 38, 20, DateTimeKind.Utc).AddTicks(5782),
                            Email = "chefhats@gmail.com",
                            Location = "21 Hougang St 51, #01-01A Hougang GREEN Shopping Mall, Singapore 538719",
                            Logo = "[\"/Images/Chef.jpg\"]",
                            OpeningHours = new TimeOnly(10, 0, 0),
                            RestaurantName = "Chef's Hats",
                            RestaurantOwnerID = "6",
                            Status = 0
                        },
                        new
                        {
                            RestaurantID = 5,
                            AdminID = 1,
                            Category = "Dessert",
                            ClosingHours = new TimeOnly(17, 30, 0),
                            Contact = 94350556,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 7, 17, 38, 20, DateTimeKind.Utc).AddTicks(5786),
                            Email = "tdp@gmail.com",
                            Location = "406 Tampines Street 41, #01-23 Sun Plaza Green, Singapore 520406",
                            Logo = "[\"/Images/tdp.jpeg\"]",
                            OpeningHours = new TimeOnly(11, 30, 0),
                            RestaurantName = "The Dessert Party",
                            RestaurantOwnerID = "7",
                            Status = 2
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<string>("ReviewTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ReviewID = 1,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 18, 15, 17, 38, 20, DateTimeKind.Local).AddTicks(5894),
                            Description = "Bad",
                            Rating = 2.5,
                            RestaurantID = 1,
                            ReviewTitle = "Bad",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "3",
                            Name = "RestaurantStaff",
                            NormalizedName = "RESTAURANTSTAFF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "6",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "7",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "8",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "9",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "10",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "11",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Dinesaur.Data.DinesaurUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Dinesaur.Data.DinesaurUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dinesaur.Data.DinesaurUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Dinesaur.Data.DinesaurUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
