// <auto-generated />
using System;
using Dinesaur.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dinesaur.Migrations
{
    [DbContext(typeof(DinesaurContext))]
    [Migration("20260118064532_a")]
    partial class a
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dinesaur.Data.DinesaurUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Contact")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8c898988-9ae3-429d-b094-06a7f9265f4c",
                            Contact = 91234567,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 6, 45, 30, 751, DateTimeKind.Utc).AddTicks(6567),
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEoTxIrfuegXj5MRr4m1NKS6UqCVElzq+SlX0uwMryEGZgicXE6NOS2sd3pvlIDF9w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eebaec41-bb74-4564-ae9d-9c4d1157eff5",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9c8f8119-d6b8-4bef-8d81-219340f3f489",
                            Contact = 91234568,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 6, 45, 30, 813, DateTimeKind.Utc).AddTicks(2845),
                            Email = "user@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "User",
                            NormalizedEmail = "USER@LOCALHOST.COM",
                            NormalizedUserName = "USER@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPmsg9yGwGPfXrq1TVKsKXHu/lqGyHT/gaXFzhaaRcsztaylGj2sYqGYya0OZ6H2Gw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2adf041a-7009-4677-9555-eefdb76a5b75",
                            TwoFactorEnabled = false,
                            UserName = "user@localhost.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "95fd72f7-2a9c-4d46-ba5c-272efc7188ba",
                            Contact = 91234560,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 6, 45, 30, 875, DateTimeKind.Utc).AddTicks(8951),
                            Email = "restaurantstaff@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "RestaurantStaff",
                            NormalizedEmail = "RESTAURANTSTAFF@LOCALHOST.COM",
                            NormalizedUserName = "RESTAURANTSTAFF@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEq3nWP5nTss/CChvJn1pb0pWacvg0x5N2Q2kIPMgdbZ8+VtRwOS/n9Kr5sE+RCADg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ec1dd817-8be3-4061-b071-d5f87b290619",
                            TwoFactorEnabled = false,
                            UserName = "restaurantstaff@localhost.com"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9a1247e8-ee38-400c-9e5c-0787ea13b942",
                            Contact = 82613992,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 6, 45, 30, 937, DateTimeKind.Utc).AddTicks(1771),
                            Email = "ButcherBlock@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "ButcherAdmin",
                            NormalizedEmail = "BUTCHERBLOCK@GMAIL.COM",
                            NormalizedUserName = "BUTCHERBLOCK@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIabe4IRvRpWqur4NOONSFqI9D6rj4ZFuIyYK6nuliQqmIAUJN9CYBdHbg4XLNBsqw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f57a9ac6-2ee2-4b0c-90f0-ac26fb6f3bdb",
                            TwoFactorEnabled = false,
                            UserName = "ButcherBlock@gmail.com"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f1604a64-2277-4112-ac55-f89e0b0ef856",
                            Contact = 88706606,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 6, 45, 30, 999, DateTimeKind.Utc).AddTicks(6936),
                            Email = "labula@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "LabulaAdmin",
                            NormalizedEmail = "LABULA@GMAIL.COM",
                            NormalizedUserName = "LABULA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEI1sUjItgNNKbTRxXdZ/qj9CAgfh4HulhVsOHg0Vug8nGkqK5UZEBW5jAhxLIuFt8Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b45480fa-a730-4c2d-9189-224523886936",
                            TwoFactorEnabled = false,
                            UserName = "labula@gmail.com"
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0439c6a8-f6c8-4063-8f3f-423c859ff6c0",
                            Contact = 94799101,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 6, 45, 31, 59, DateTimeKind.Utc).AddTicks(6202),
                            Email = "chefhats@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "ChefHatsAdmin",
                            NormalizedEmail = "CHEFHATS@GMAIL.COM",
                            NormalizedUserName = "CHEFHATS@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHPVSW8dg12nh8OzO4iwj+jLkK0C9OBDdfF9vqSj+5KnS8JQU+BkDwRfkcv0Gp8iDA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "38074659-4791-49d5-baa3-529b1b6af9d3",
                            TwoFactorEnabled = false,
                            UserName = "chefhats@gmail.com"
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8acbcb87-fdc7-4676-a672-2567be3ebfbd",
                            Contact = 91234560,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 6, 45, 31, 122, DateTimeKind.Utc).AddTicks(7549),
                            Email = "tdp@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "TDPAdmin",
                            NormalizedEmail = "TDP@GMAIL.COM",
                            NormalizedUserName = "TDP@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECWZQngElL0GAK/D/7qZblkWuA+FwCrT8flrY39b0oaUle3pUj01zpdB6npELcdd8A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f3637f15-940d-4d41-b73a-d71234611a5b",
                            TwoFactorEnabled = false,
                            UserName = "tdp@gmail.com"
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.DinesaurUserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Contact")
                        .HasColumnType("int");

                    b.Property<string>("DinesaurUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DinesaurUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DinesaurUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contact = 91234568,
                            DinesaurUserID = "2",
                            DinesaurUserName = "User",
                            Email = "user@localhost.com"
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Food", b =>
                {
                    b.Property<int>("FoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<string>("StaffID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodID");

                    b.ToTable("Food");

                    b.HasData(
                        new
                        {
                            FoodID = 1,
                            Category = "Meat",
                            Cost = 3.5,
                            Description = "White meat",
                            FoodName = "Chicken",
                            Image = "[]",
                            MenuID = 9999,
                            StaffID = "999"
                        },
                        new
                        {
                            FoodID = 2,
                            Category = "Seafood",
                            Cost = 4.0,
                            Description = "Saba",
                            FoodName = "Fish",
                            Image = "[]",
                            MenuID = 999,
                            StaffID = "9999"
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Menu", b =>
                {
                    b.Property<int>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Catergories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.HasKey("MenuID");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            MenuID = 1,
                            Category = "",
                            Catergories = "[]",
                            RestaurantID = 999
                        },
                        new
                        {
                            MenuID = 2,
                            Category = "",
                            Catergories = "[]",
                            RestaurantID = 9998
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.PreOrder", b =>
                {
                    b.Property<int>("PreOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreOrderID"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.HasKey("PreOrderID");

                    b.ToTable("PreOrder");

                    b.HasData(
                        new
                        {
                            PreOrderID = 1,
                            Cost = 3.5,
                            MenuID = 1,
                            Remarks = "Please remove the onions",
                            ReservationID = 1
                        },
                        new
                        {
                            PreOrderID = 2,
                            Cost = 4.0,
                            MenuID = 2,
                            Remarks = "Please remove all vegetables",
                            ReservationID = 2
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.PreOrderItem", b =>
                {
                    b.Property<int>("PreorderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreorderItemID"));

                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.Property<int>("PreOrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("PreorderItemID");

                    b.ToTable("PreOrderItem");

                    b.HasData(
                        new
                        {
                            PreorderItemID = 1,
                            FoodID = 1,
                            PreOrderID = 1,
                            Quantity = 1
                        },
                        new
                        {
                            PreorderItemID = 2,
                            FoodID = 1,
                            PreOrderID = 1,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("Pax")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("Time")
                        .IsRequired()
                        .HasColumnType("time");

                    b.HasKey("ReservationID");

                    b.ToTable("Reservation");

                    b.HasData(
                        new
                        {
                            ReservationID = 1,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 9, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 4,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 1,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 2,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 2,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 0,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 3,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 13, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 3,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 3,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 4,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 4,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 0,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 5,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 2,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 1,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 6,
                            CustomerID = "2",
                            Date = new DateTime(2025, 12, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 2,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 3,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 7,
                            CustomerID = "2",
                            Date = new DateTime(2025, 12, 22, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 4,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 3,
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            ReservationID = 8,
                            CustomerID = "2",
                            Date = new DateTime(2025, 12, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Pax = 3,
                            Remarks = "N/A",
                            RestaurantID = 1,
                            Status = 3,
                            Time = new TimeOnly(12, 30, 0)
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Restaurant", b =>
                {
                    b.Property<int>("RestaurantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantID"));

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("ClosingHours")
                        .HasColumnType("time");

                    b.Property<int?>("Contact")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("OpeningHours")
                        .HasColumnType("time");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantOwnerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RestaurantID");

                    b.ToTable("Restaurant");

                    b.HasData(
                        new
                        {
                            RestaurantID = 1,
                            AdminID = 1,
                            Category = "Western",
                            ClosingHours = new TimeOnly(22, 0, 0),
                            Contact = 82613992,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 6, 45, 30, 751, DateTimeKind.Utc).AddTicks(6062),
                            Email = "tomahawk@gmail.com",
                            Location = "273, #01-06 Thomson Rd, Novena Gardens, Singapore 307644",
                            Logo = "[\"/Images/Tomahawk.jpeg\"]",
                            OpeningHours = new TimeOnly(12, 0, 0),
                            RestaurantName = "Tomahawk Contemporary Steakhouse",
                            RestaurantOwnerID = "3",
                            Status = 1
                        },
                        new
                        {
                            RestaurantID = 2,
                            AdminID = 1,
                            Category = "Fine Dining",
                            ClosingHours = new TimeOnly(21, 30, 0),
                            Contact = 64121816,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 6, 45, 30, 751, DateTimeKind.Utc).AddTicks(6076),
                            Email = "ButcherBlock@gmail.com",
                            Location = "328 N Bridge Rd, #02-02 RAFFLES ARCADE, Singapore 188719",
                            Logo = "[\"/Images/Butcher.jpg\"]",
                            OpeningHours = new TimeOnly(12, 0, 0),
                            RestaurantName = "Butcher's Block",
                            RestaurantOwnerID = "4",
                            Status = 1
                        },
                        new
                        {
                            RestaurantID = 3,
                            AdminID = 1,
                            Category = "HotPot",
                            ClosingHours = new TimeOnly(22, 30, 0),
                            Contact = 88706606,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 6, 45, 30, 751, DateTimeKind.Utc).AddTicks(6082),
                            Email = "labula@gmail.com",
                            Location = "681 Punggol Dr., #01-07, Singapore 820681",
                            Logo = "[\"/Images/LABULA.jpg\"]",
                            OpeningHours = new TimeOnly(10, 30, 0),
                            RestaurantName = "辣不辣 Labula Mala Sichuan Restaurant",
                            RestaurantOwnerID = "5",
                            Status = 1
                        },
                        new
                        {
                            RestaurantID = 4,
                            AdminID = 1,
                            Category = "Western",
                            ClosingHours = new TimeOnly(22, 0, 0),
                            Contact = 94799101,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 6, 45, 30, 751, DateTimeKind.Utc).AddTicks(6086),
                            Email = "chefhats@gmail.com",
                            Location = "21 Hougang St 51, #01-01A Hougang GREEN Shopping Mall, Singapore 538719",
                            Logo = "[\"/Images/Chef.jpg\"]",
                            OpeningHours = new TimeOnly(10, 0, 0),
                            RestaurantName = "Chef's Hats",
                            RestaurantOwnerID = "6",
                            Status = 0
                        },
                        new
                        {
                            RestaurantID = 5,
                            AdminID = 1,
                            Category = "Dessert",
                            ClosingHours = new TimeOnly(17, 30, 0),
                            Contact = 94350556,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 6, 45, 30, 751, DateTimeKind.Utc).AddTicks(6089),
                            Email = "tdp@gmail.com",
                            Location = "406 Tampines Street 41, #01-23 Sun Plaza Green, Singapore 520406",
                            Logo = "[\"/Images/tdp.jpeg\"]",
                            OpeningHours = new TimeOnly(11, 30, 0),
                            RestaurantName = "The Dessert Party",
                            RestaurantOwnerID = "7",
                            Status = 2
                        });
                });

            modelBuilder.Entity("Dinesaur.Domain.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<string>("ReviewTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ReviewID = 1,
                            CustomerID = "2",
                            Date = new DateTime(2026, 1, 18, 14, 45, 30, 751, DateTimeKind.Local).AddTicks(6315),
                            Description = "Bad",
                            Rating = 2.5,
                            RestaurantID = 1,
                            ReviewTitle = "Bad",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "3",
                            Name = "RestaurantStaff",
                            NormalizedName = "RESTAURANTSTAFF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "6",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "7",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Dinesaur.Data.DinesaurUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Dinesaur.Data.DinesaurUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dinesaur.Data.DinesaurUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Dinesaur.Data.DinesaurUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
